name: reboot_launcher
description: Launcher for project reboot
version: "6.4.0"

publish_to: 'none'

environment:
  sdk: ">=2.17.6 <=3.3.3"

dependencies:
  flutter:
    sdk: flutter

  bitsdojo_window:
    path: ./dependencies/bitsdojo_window-0.1.5
  fluent_ui: ^4.1.3
  bitsdojo_window_windows: ^0.1.5
  system_theme: ^2.0.0
  http: ^0.13.5
  html: ^0.15.0
  shared_preferences: ^2.0.15
  file_picker: ^5.2.0+1
  context_menus: ^1.0.1
  process_run: ^0.12.3+2
  url_launcher: ^6.1.5
  archive: ^3.3.1
  version: ^3.0.2
  crypto: ^3.0.2
  async: ^2.8.2
  get: ^4.6.5
  get_storage: ^2.0.3
  window_manager: ^0.2.7
  shelf_proxy: ^1.0.2
  args: ^2.3.1
  win32: 3.0.0
  clipboard: ^0.1.3
  sync: ^0.3.0
  ini: ^2.1.0
  universal_disk_space: ^0.2.3
  jaguar: ^3.1.3
  hex: ^0.2.0
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  msix: ^3.6.3

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/binaries/
    - assets/images/
    - assets/profiles/
    - assets/responses/
    - assets/config/

msix_config:
  display_name: Reboot Launcher
  publisher_display_name: Auties00
  identity_name: 31868Auties00.RebootLauncher
  msix_version: 6.4.0.0
  publisher: CN=E6CD08C6-DECF-4034-A3EB-2D5FA2CA8029
  logo_path: ./assets/icons/reboot.ico
  architecture: x64
  store: true
  capabilities: "internetClient"